
import { EpisodeMetadata } from './types';

const EP1_DATA = [
  { "Time": "25s", "Subtitle": "♪ There she goes ♪", "Human Translation": "좋은 음식 루크네" },
  { "Time": "29s", "Subtitle": "♪ There she goes again ♪", "Human Translation": "루크네" },
  { "Time": "48s", "Subtitle": "Please, Luke. Please, please, please.", "Human Translation": "부탁이에요, 루크" },
  { "Time": "50s", "Subtitle": "How many cups have you had today?", "Human Translation": "오늘 커피는 몇 잔 마셨죠?" },
  { "Time": "52s", "Subtitle": "- None. - 'Plus.'", "Human Translation": "- 전혀요 - 진실은?" },
  { "Time": "54s", "Subtitle": "Five, but yours is better.", "Human Translation": "5잔이오 하지만 여기가 더 맛있어요" },
  { "Time": "56s", "Subtitle": "- You have a problem. - Yes, I do.", "Human Translation": "- 심각하군요 - 알아요" },
  { "Time": "1:00", "Subtitle": "- 'Junkie.' - Angel.", "Human Translation": "- 중독자 - 천사님" },
  { "Time": "1:02", "Subtitle": "You've got wings, baby.", "Human Translation": "날개가 보여요" },
  { "Time": "1:07", "Subtitle": "Luke's? Yeah.", "Human Translation": "루크입니다, 네" },
  { "Time": "1:13", "Subtitle": "You make that look really good.", "Human Translation": "맛있게 드시네요" },
  { "Time": "1:15", "Subtitle": "Oh, it is really good. It's the best coffee in town.", "Human Translation": "진짜 맛있어요 동네 최고의 커피죠" },
  { "Time": "1:18", "Subtitle": "- Oh, yeah? I'll get a cup. - Good plan.", "Human Translation": "- 저도 마셔 볼게요 - 좋은 생각이네요" },
  { "Time": "1:21", "Subtitle": "Yeah, I've never been here before.", "Human Translation": "전 여기 처음이에요" },
  { "Time": "1:23", "Subtitle": "Just, uh, passing through on my way to Hartford.", "Human Translation": "하트포드 가는 길에 들린 거죠" },
  { "Time": "1:25", "Subtitle": "You're a regular Jack Kerouac.", "Human Translation": "완전히 모험가군요" },
  { "Time": "1:29", "Subtitle": "You mind if I sit down? Oh, you know what? Actually, I'm meeting someone so I..", "Human Translation": "- 앉아도 될까요? - 전 약속이 있어서…" },
  { "Time": "1:33", "Subtitle": "- I'm Joey. - Okay.", "Human Translation": "- 조이입니다 - 그렇군요" },
  { "Time": "1:36", "Subtitle": "- What, you don't have a name? - No, I do have a name.", "Human Translation": "이름도 없으세요? 이름은 있지만 정말 약속이 있어요" },
  { "Time": "1:39", "Subtitle": "I just, I'm really meeting someone, so..", "Human Translation": "이름은 있지만 정말 약속이 있어요" },
  { "Time": "1:40", "Subtitle": "So I guess I should get going.", "Human Translation": "일어서란 뜻이군요" },
  { "Time": "1:42", "Subtitle": "- So soon? - What?", "Human Translation": "- 벌써요? - 네?" },
  { "Time": "1:44", "Subtitle": "I'm just screwing with your mind.", "Human Translation": "그냥 장난이에요 만나서 반가웠어요" },
  { "Time": "1:46", "Subtitle": "It's nice to meet you. Enjoy Hartford.", "Human Translation": "하트포드까지 잘 가요" },
  { "Time": "1:48", "Subtitle": "Enjoy your coffee, mystery woman.", "Human Translation": "커피 드세요, 신비의 여인" },
  { "Time": "1:51", "Subtitle": "Hm. I like that.", "Human Translation": "마음에 드네요" },
  { "Time": "1:55", "Subtitle": "Hey. It's freezing. Oh, what do you need? Hot tea, coffee?", "Human Translation": "- 추워 죽겠네 - 뜨거운 차나 커피라도 줄까?" },
  { "Time": "1:59", "Subtitle": "- Lip gloss. - Aha.", "Human Translation": "립글로스" },
  { "Time": "2:03", "Subtitle": "I have vanilla, chocolate, strawberry and toasted marshmallow.", "Human Translation": "바닐라, 초콜릿, 딸기하고 구운 마시맬로 향이야" },
  { "Time": "2:06", "Subtitle": "Anything in there not resembling a breakfast cereal?", "Human Translation": "아침 식사 맛 말고 다른 건 없어?" },
  { "Time": "2:08", "Subtitle": "Yes. It has no smell but it changes colors with your mood.", "Human Translation": "있어, 향은 없지만 기분에 따라 색이 변하는 거야" },
  { "Time": "2:12", "Subtitle": "RuPaul doesn't need this much makeup. You're crabby.", "Human Translation": "- 성전환자보다도 화장품이 많네 - 버릇없는 것" },
  { "Time": "2:16", "Subtitle": "I'm sorry. I lost my Macy Gray CD and I need caffeine.", "Human Translation": "메이시 그레이 CD가 사라졌어 카페인이 필요해" },
  { "Time": "2:19", "Subtitle": "- I have your CD. - Thief.", "Human Translation": "- CD는 여기 있어 - 도둑 같으니" },
  { "Time": "2:21", "Subtitle": "Sorry, I'll get you some coffee.", "Human Translation": "미안, 대신 커피를 갖다 줄게" },
  { "Time": "2:27", "Subtitle": "What? It's not for me. It's for Rory, I swear.", "Human Translation": "하늘에 맹세코 제가 아니라 로리 커피예요" },
  { "Time": "2:30", "Subtitle": "- You're shameless. - Look, Officer Krupke.", "Human Translation": "- 뻔뻔하군요 - 이것 봐요, 경찰 아저씨" },
  { "Time": "2:32", "Subtitle": "She's right at that table, right over there.", "Human Translation": "로리는 바로 저기 있잖아요" },
  { "Time": "2:36", "Subtitle": "Ah. He's got quite a pair, this guy. Thanks.", "Human Translation": "꽤나 대담한 양반이군 고마워요" },
  { "Time": "2:42", "Subtitle": "Yeah, I've never been through here before. Oh, you have, too.", "Human Translation": "- 전 여기 처음이에요 - 아까도 처음이었죠?" },
  { "Time": "2:45", "Subtitle": "- Oh, hi. - Oh, hi.", "Human Translation": "안녕하세요" },
  { "Time": "2:47", "Subtitle": "You really like my table, don't you? I was just, uh..", "Human Translation": "- 이 자리가 좋은가 보죠? - 전 단지…" },
  { "Time": "2:50", "Subtitle": "Getting to know my daughter.", "Human Translation": "제 딸과 좀 친해졌나요?" },
  { "Time": "2:51", "Subtitle": "- Your.. - Are you my new daddy?", "Human Translation": "아저씨가 새아빠예요?" },
  { "Time": "2:54", "Subtitle": "Wow. You do not look old enough to have a daughter.", "Human Translation": "딸이 있을 나이로는 안 보이네요" },
  { "Time": "2:58", "Subtitle": "No, I mean it. And you do not look like a daughter.", "Human Translation": "진심이에요 그쪽도 따님처럼은 안 보여요" },
  { "Time": "3:02", "Subtitle": "That's possibly very sweet of you. Thanks.", "Human Translation": "고마운 말처럼 들리네요" },
  { "Time": "3:06", "Subtitle": "So...daughter.", "Human Translation": "딸이라고 하셨죠?" },
  { "Time": "3:10", "Subtitle": "You know, I am traveling with a friend. - She's sixteen. - Bye.", "Human Translation": "- 실은 동행이 하나 있는데… - 딸은 16살이에요" },
  { "Time": "3:14", "Subtitle": "Drive safe.", "Human Translation": "운전 조심해요" },
  { "Time": "4:30", "Subtitle": "- Here you go. - Thanks.", "Human Translation": "- 받아요 - 고맙습니다" },
  { "Time": "4:32", "Subtitle": "Independence Inn, Michel speaking.", "Human Translation": "인디펜던스 모텔의 미셸입니다" },
  { "Time": "4:36", "Subtitle": "No, I'm sorry, we're completely booked.", "Human Translation": "죄송합니다만 예약이 꽉 찼군요" },
  { "Time": "4:38", "Subtitle": "We have a wedding party here.", "Human Translation": "결혼식이 있거든요" },
  { "Time": "4:41", "Subtitle": "No, there is really nothing I can do.", "Human Translation": "아뇨, 도와드릴 수가 없네요" },
  { "Time": "4:43", "Subtitle": "Yes, I'm sure. Positive.", "Human Translation": "네, 정말입니다 확실하죠" },
  { "Time": "4:54", "Subtitle": "No, I'm sorry, we're completely booked.", "Human Translation": "죄송합니다만 빈방이 없네요" },
  { "Time": "4:57", "Subtitle": "(female #1) 'Oh, no, don't move.'", "Human Translation": "비키지 말아요" },
  { "Time": "4:58", "Subtitle": "Just ignore the tiny woman pushing the 200-pound instrument around.", "Human Translation": "큰 악기에 달라붙은 작은 여자 따위는 무시해야죠" },
  { "Time": "5:12", "Subtitle": "Hi, Drella, hi.", "Human Translation": "- 왔어요, 드렐라? - 네" },
  { "Time": "5:13", "Subtitle": "I was just wondering, um, could you be, uh, nicer to the guests?", "Human Translation": "혹시 손님들에게 조금 친절하게 대할 수 있을까요?" },
  { "Time": "5:18", "Subtitle": "I'm sorry. Did you not want a harp player?", "Human Translation": "하프 연주자를 부른 게 아니었나요?" },
  { "Time": "5:20", "Subtitle": "Yes, I did.", "Human Translation": "불렀죠" },
  { "Time": "5:21", "Subtitle": "And did you not want a great harp player?", "Human Translation": "훌륭한 연주자를 불렀죠?" },
  { "Time": "5:24", "Subtitle": "Yes, I did. Okay. I am a great harp player.", "Human Translation": "내가 그 훌륭한 연주자예요" },
  { "Time": "5:28", "Subtitle": "And this is my great harp, okay?", "Human Translation": "이건 제 훌륭한 하프죠" },
  { "Time": "5:30", "Subtitle": "So if you're looking for someone to be nice to the guests", "Human Translation": "그러니 손님에게 친절한 연주자를 원한다면" },
  { "Time": "5:37", "Subtitle": "Okay? Capish?", "Human Translation": "알아들었죠?" },
  { "Time": "5:40", "Subtitle": "Oh, that is a great spot for a table. Decorator's a genius.", "Human Translation": "탁자 놓기 딱 좋은 자리네요 환상적인 인테리어에요" },
  { "Time": "6:11", "Subtitle": "Has the plumber attended to room four yet? He was here, he did nothing, it's a hundred dollars.", "Human Translation": "- 4호실에 배관공이 왔나요? - 그냥 보기만 하고 백 달러래요" },
  { "Time": "6:19", "Subtitle": "Hi, Marco, Lorelai. Talk to me about room four.", "Human Translation": "마르코, 로렐라이에요 4호실은 뭐가 문제였죠?" },
  { "Time": "6:31", "Subtitle": "So this one's on you, right?", "Human Translation": "그럼 이번엔 공짜죠?" },
  { "Time": "6:33", "Subtitle": "Pleasure doing business with you.", "Human Translation": "도와줘서 정말 고마웠어요" },
  { "Time": "6:35", "Subtitle": "- What is your offspring doing? - Need stamps. I'll take these?", "Human Translation": "- 애는 왜 데려왔죠? - 이 우표 써도 돼요?" },
  { "Time": "6:40", "Subtitle": "- What's with the muumuu? - Stop.", "Human Translation": "- 원주민 의상이네? - 그만해" },
  { "Time": "6:47", "Subtitle": "Hey, have Michel look at your French paper before you go.", "Human Translation": "가기 전에 미셸한테 불어 숙제를 맡겨" },
  { "Time": "6:54", "Subtitle": "I'll tell all the ladies what a stud you are.", "Human Translation": "부탁해요, 여자들한테 미셸이 힘 좋다고 소문 낼게요" },
  { "Time": "7:04", "Subtitle": "Leave it. I'll look at it if I get a chance.", "Human Translation": "놓고 가 시간 나면 훑어볼게" },
  { "Time": "7:14", "Subtitle": "- I despise you. - Hm.", "Human Translation": "미워 죽겠네요" },
  { "Time": "9:31", "Subtitle": "Oh, why aren't you watching her?", "Human Translation": "잘 좀 보지 그랬어요?" },
  { "Time": "9:39", "Subtitle": "I need you to be more careful.", "Human Translation": "- 좀 더 조심해" },
  { "Time": "9:57", "Subtitle": "Okay. Oh, Sookie, I need you to be more careful.", "Human Translation": "수키, 앞으로는 더 조심해" },
  { "Time": "10:18", "Subtitle": "- Won't that be great? - Yeah.", "Human Translation": "정말 멋질 거야" },
  { "Time": "10:29", "Subtitle": "So, now, let's get you up and to the doctor on three. - One, two, three. - Ow!", "Human Translation": "이제 일어나서 병원에 가자 하나, 둘, 셋!" },
  { "Time": "10:46", "Subtitle": "Oh, well, there's no way Mark Twain can compete with that.", "Human Translation": "마크 트웨인 같으면 어림도 없겠는걸" },
  { "Time": "13:05", "Subtitle": "O-oh, It's here. It happened. She did it.", "Human Translation": "드디어 도착했어 그 애가 해냈어!" },
  { "Time": "13:10", "Subtitle": "The Chilton school. Rory got in.", "Human Translation": "칠튼 고등학교에 로리가 합격했어" },
  { "Time": "13:30", "Subtitle": "This is very exciting.", "Human Translation": "정말 좋은 일이야" },
  { "Time": "14:13", "Subtitle": "- Mom? - You did it, babe. You got in.", "Human Translation": "정말이야? 네가 해냈어, 입학이야" },
  { "Time": "14:28", "Subtitle": "I don't believe this. Oh my God, I'm going to Chilton! Yeah.", "Human Translation": "믿을 수가 없어 세상에, 내가 칠튼에?" },
  { "Time": "14:46", "Subtitle": "- My girl's going to Chilton. - Yeah. Rory's going to Chilton!", "Human Translation": "내 딸이 칠튼에 간대 그래, 로리가 칠튼에 간다!" },
  { "Time": "16:50", "Subtitle": "What do I do? What do I do? What do I do?", "Human Translation": "어떡하지?" },
  { "Time": "17:13", "Subtitle": "Can I say something? It's really your only option.", "Human Translation": "한 마디만 더 할게 방법은 그것밖에 없어" },
  { "Time": "17:20", "Subtitle": "to that option.", "Human Translation": "그 방법은 싫어" },
  { "Time": "17:33", "Subtitle": "You look like you were swallowed by a kilt.", "Human Translation": "스코틀랜드 남자 치마 같아" },
  { "Time": "17:47", "Subtitle": "I know.", "Human Translation": "그러게" },
  { "Time": "21:03", "Subtitle": "Yeah.", "Human Translation": "맞아요" },
  { "Time": "21:21", "Subtitle": "- On one condition. - So close.", "Human Translation": "- 조건이 있어 - 그러면 그렇지" },
  { "Time": "22:11", "Subtitle": "Perfect.", "Human Translation": "좋아요" },
  { "Time": "23:41", "Subtitle": "Hi.", "Human Translation": "안녕" },
  { "Time": "24:05", "Subtitle": "I never talk this much.", "Human Translation": "난 원래는 말이 없어" },
  { "Time": "43:08", "Subtitle": "No, mom, he's a mime.", "Human Translation": "아니, 우린 마임으로 통해" }
];

const EP2_DATA = [
  { "Time": "2s", "Subtitle": "NOBODY DEMANDED THAT YOU COME. ARE YOU KIDDING?", "Human Translation": "‎- 학용품 쇼핑이라, 완전히 파티네 ‎- 엄마한테 같이 가자고 안 했어" },
  { "Time": "4s", "Subtitle": "HOW OFTEN DO YOU GET TO DO THIS?", "Human Translation": "‎무슨 소리야? ‎이런 거 할 기회가 많은 줄 알아?" },
  { "Time": "6s", "Subtitle": "WHILE WE'RE GOING CRAZY, WE SHOULD GET TOILET PAPER AND A PLUNGER.", "Human Translation": "‎이왕 이렇게 된 김에 ‎화장실 휴지하고 변기 뚫는 것도 사자" },
  { "Time": "10s", "Subtitle": "I'LL DO THIS LATER. NO. I'M TEASING.", "Human Translation": "‎나중에 올래" },
  { "Time": "12s", "Subtitle": "GET THAT LIST OF YOURS. OKAY. AHEM.", "Human Translation": "‎- 장난친 거야, 쇼핑 목록 줘 봐 ‎- 좋아" },
  { "Time": "16s", "Subtitle": "I NEED LEGAL PADS. GOT IT.", "Human Translation": "‎- 연습장하고… ‎- 알았어" },
  { "Time": "18s", "Subtitle": "TONS OF PENS. RIGHT. SOME PENCILS, THREE HIGHLIGHTERS, AN ERASER,", "Human Translation": "‎연필 잔뜩, H2 연필 약간 ‎형광펜 세 개, 지우개…" },
  { "Time": "22s", "Subtitle": "A STAPLE REMOVER, AND A FOLDER.", "Human Translation": "‎스테이플 빼는 거 하고 파일이야" },
  { "Time": "25s", "Subtitle": "YOU NEED THREE HIGHLIGHTERS? THREE? YES.", "Human Translation": "‎- 형광펜 세 개? ‎- 응" },
  { "Time": "27s", "Subtitle": "THAT'S A VERY RANDOM NUMBER. THREE IS NOT A RANDOM NUMBER.", "Human Translation": "‎- 왜 하필이면 세 개야? ‎- 세 개가 뭐 어때서?" },
  { "Time": "31s", "Subtitle": "ONE DRIES UP, ONE GETS LOST, I HAVE ONE LEFT.", "Human Translation": "‎하나씩 마르고 잃어버려도 ‎하나가 남잖아" },
  { "Time": "34s", "Subtitle": "YOU'VE REALLY THOUGHT THIS OUT.", "Human Translation": "‎- 고심한 흔적이 보이네 ‎- 맞아" },
  { "Time": "37s", "Subtitle": "CAN WE GET BACK TO THE LIST? ALRIGHT. OOH, HEY -- LEGAL PADS.", "Human Translation": "‎- 필요한 것부터 사면 안 될까? ‎- 그래, 맞아, 연습장" },
  { "Time": "41s", "Subtitle": "NO. THOSE ARE PURPLE. PURPLE IS FESTIVE. I CAN'T HAVE PURPLE.", "Human Translation": "‎- 보라색은 안 돼 ‎- 보라색은 화려하잖아" },
  { "Time": "46s", "Subtitle": "I'M GOING TO A SERIOUS SCHOOL. I NEED SERIOUS PAPER.", "Human Translation": "‎분위기가 진지한 학교라 ‎진지한 연습장을 써야 해" },
  { "Time": "49s", "Subtitle": "PAPER IS PAPER. NOT AT CHILTON.", "Human Translation": "‎- 그래 봐야 종이잖아 ‎- 칠튼에선 아냐" },
  { "Time": "51s", "Subtitle": "ALRIGHT, FINE. HERE'S YOUR SERIOUS PAPER. THANK YOU.", "Human Translation": "‎- 좋아, 그럼 진지한 연습장으로 ‎- 고마워" },
  { "Time": "54s", "Subtitle": "OOH, AND HERE ARE YOUR SOMBER HIGHLIGHTERS,", "Human Translation": "‎어두컴컴한 형광펜하고 ‎감상적인 연필…" },
  { "Time": "57s", "Subtitle": "YOUR MAUDLIN PENCILS, YOUR MANIC-DEPRESSIVE PENS. MOM.", "Human Translation": "‎어두컴컴한 형광펜하고 ‎감상적인 연필… ‎- 조울증에 걸린 연필이 있네 ‎- 엄마" },
  { "Time": "1:07", "Subtitle": "I'M GOING HOME. NO, WAIT.", "Human Translation": "‎- 집에 갈래 ‎- 기다려" },
  { "Time": "1:14", "Subtitle": "YOU'RE NEVER COMING SHOPPING WITH ME AGAIN.", "Human Translation": "‎다시는 엄마랑 쇼핑 안 해" },
  { "Time": "1:54", "Subtitle": "♪ WHERE YOU LEAD, I WILL FOLLOW ♪", "Human Translation": "‎켈리 비숍 ‎에드워드 허먼" },
  { "Time": "3:03", "Subtitle": "MISS GILMORE, TAKE THESE HOME. LEARN FROM YOUR MISTAKES.", "Human Translation": "‎길모어 양, 집에 가서 ‎틀린 문제를 복습하도록 해" },
  { "Time": "4:10", "Subtitle": "A JOB APPLICATION AT McDONALD'S.", "Human Translation": "‎맥도날드에나 취직해야지, 뭐" },
  { "Time": "4:29", "Subtitle": "HEY, MARY!", "Human Translation": "‎안녕, 메리!" },
  { "Time": "4:56", "Subtitle": "PLEASE LEAVE ME ALONE.", "Human Translation": "‎제발 귀찮게 하지 말아 줘" },
  { "Time": "5:29", "Subtitle": "YOU'RE FIRED! EXCUSE ME?", "Human Translation": "‎- 해고야! ‎- 당신이 뭔데 해고해요?" },
  { "Time": "5:53", "Subtitle": "OH, MY GOD.", "Human Translation": "‎어머나" },
  { "Time": "7:22", "Subtitle": "I CAN'T. I HAVE TO STUDY.", "Human Translation": "‎난 공부 때문에 안 돼" },
  { "Time": "8:28", "Subtitle": "LORELAI, GO TO YOUR ROOM.", "Human Translation": "‎로렐라이, 네 방으로 가!" },
  { "Time": "9:03", "Subtitle": "WHAT?", "Human Translation": "‎왜?" },
  { "Time": "10:40", "Subtitle": "I REALLY MISS STARS HOLLOW HIGH.", "Human Translation": "‎스타즈 할로우 고등학교가 정말 그리워" },
  { "Time": "11:10", "Subtitle": "UM, SO...THIS GUY ASKED ABOUT YOU TODAY.", "Human Translation": "‎- 그 애가 너에 대해 묻더라 ‎- 어떤 애?" },
  { "Time": "12:51", "Subtitle": "ISN'T IT? NO, IT'S NOT FINE.", "Human Translation": "‎- 내 리조토가 좋다고 했잖아 ‎- 그럼 안 좋아? ‎좋으면 안 돼" },
  { "Time": "13:59", "Subtitle": "MORELS ARE FINE.", "Human Translation": "‎곰보버섯도 좋아요" },
  { "Time": "15:47", "Subtitle": "That was really bad coffee.", "Human Translation": "‎커피 맛이 별로예요" },
  { "Time": "16:20", "Subtitle": "YEAH. IT'S A BIG, EXCITING TEST.", "Human Translation": "‎기대되는 중요한 시험이니 ‎부모도 참관하면…" },
  { "Time": "17:12", "Subtitle": "NOT IN MY WORLD.", "Human Translation": "‎전 그렇게 못해요" },
  { "Time": "18:40", "Subtitle": "I KNOW A \"D\" SEEMS DISMAL -- RORY GOT A \"D?\"", "Human Translation": "‎- 로리가 D학점을… ‎- 로리가 D를 받아요?" },
  { "Time": "21:17", "Subtitle": "IT WAS...A \"D.\" I GOT A \"D.\"", "Human Translation": "‎D야, D를 받았다고" },
  { "Time": "22:50", "Subtitle": "WELL, YOU DID GET A \"D.\"", "Human Translation": "‎뭐, D도 받아 봤잖아" },
  { "Time": "25:31", "Subtitle": "NOT ONE MISTAKE. WOW!", "Human Translation": "‎- 하나도 안 틀렸어, 기분이 어때? ‎- 구역질 나" },
  { "Time": "27:41", "Subtitle": "I'M LATE! WHAT?", "Human Translation": "‎- 늦었어! ‎- 뭐?" },
  { "Time": "29:11", "Subtitle": "NO! I GOT HIT BY A DEER! HOW DO YOU GET HIT BY A DEER?", "Human Translation": "‎- 아니, 사슴이 부딪쳤다고 ‎- 어떻게 사슴이 부딪쳐?" },
  { "Time": "30:23", "Subtitle": "YOU HIT A DEER? I GOT HIT BY A DEER.", "Human Translation": "‎- 사슴을 쳤다고? ‎- 아뇨, 사슴이 와서 부딪쳤어요" },
  { "Time": "30:57", "Subtitle": "AND, FOR THE LAST TIME, THE NAME IS RORY!", "Human Translation": "‎마지막으로 말하는데 ‎내 이름은 로리야!" },
  { "Time": "33:00", "Subtitle": "RORY, WHAT HAPPENED?", "Human Translation": "‎로리, 무슨 일이야?" },
  { "Time": "37:04", "Subtitle": "YOU GOT HIT BY A DEER?", "Human Translation": "‎사슴이 와서 부딪쳤다고?" },
  { "Time": "42:56", "Subtitle": "Anyway, see you in class. Bye.", "Human Translation": "‎'어쨌든 학교에서 보자, 안녕'" }
];

const EP3_DATA = [
  { "Time": "1s", "Subtitle": "DINNER WAS LOVELY, EMILY. MIRA DOES MAKE A PERFECT CASSOULET.", "Human Translation": "- 맛있는 저녁이었소, 에밀리 - 미라의 카술레는 별미죠" },
  { "Time": "8s", "Subtitle": "I THOUGHT THE COOK WAS HEIDI. WE LET HEIDI GO MONTHS AGO.", "Human Translation": "- 요리사는 하이디였잖아요 - 하이디는 몇 달 전에 잘랐어" },
  { "Time": "17s", "Subtitle": "THEN IT WAS TRINA, THEN SOPHIA. I LIKED SOPHIA.", "Human Translation": "- 그 후엔 트리나, 소피아였지 - 소피아가 괜찮았죠" },
  { "Time": "33s", "Subtitle": "I'M SORRY, DAD. HOW DO YOU MIX UP ANTON AND SOPHIA?", "Human Translation": "아빠, 어떻게 안톤과 소피아를 혼동할 수가 있죠?" },
  { "Time": "53s", "Subtitle": "BUT ONE IS A MAN, AND ONE IS A WOMAN.", "Human Translation": "하지만 남자와 여자라는 차이가 있잖아요" },
  { "Time": "1:12", "Subtitle": "GRANDMA, THESE PLATES ARE REALLY PRETTY.", "Human Translation": "할머니, 접시가 정말 예쁘네요" },
  { "Time": "1:24", "Subtitle": "BUT IN MANY OTHER THINGS, I WAS A TRAILBLAZER.", "Human Translation": "그래, 하지만 다른 면에서 난 뭐든지 선구자였지" },
  { "Time": "1:40", "Subtitle": "SHE WAS QUITE A WOMAN.", "Human Translation": "어머님은 대단한 분이셨단다" },
  { "Time": "2:46", "Subtitle": "SO, LORELAI, HOW ARE THINGS AT THAT CHARMING LITTLE INN OF YOURS?", "Human Translation": "로렐라이, 그 작고 예쁜 모텔은 요즘 어떠니?" },
  { "Time": "3:03", "Subtitle": "YEAH. RORY, HOW'S CHILTON?", "Human Translation": "- 로리, 칠튼은 어떠니? - 내 상대는 끝이군요" },
  { "Time": "3:20", "Subtitle": "I'M NOT SURE. I'M NOT REALLY THE ATHLETIC TYPE.", "Human Translation": "잘 모르겠어요 운동엔 소질이 없거든요" },
  { "Time": "3:37", "Subtitle": "GOLF? YEAH.", "Human Translation": "- 골프라고? - 네" },
  { "Time": "4:02", "Subtitle": "OKAY. MOM, COULD I MAYBE TALK TO YOU FOR A MINUTE?", "Human Translation": "엄마, 잠깐 얘기 좀 할까요?" },
  { "Time": "4:23", "Subtitle": "DON'T DO THIS, MOM. DO WHAT?", "Human Translation": "- 이러지 말아요, 엄마 - 뭘?" },
  { "Time": "4:52", "Subtitle": "THAT RORY WILL ENJOY THE CLUB AND HAVE A GOOD TIME WITHOUT YOU.", "Human Translation": "로리가 너도 없는데 클럽을 좋아할까 봐" },
  { "Time": "5:31", "Subtitle": "SO LET ME GET THIS STRAIGHT --", "Human Translation": "그럼 정리해 보자" },
  { "Time": "6:06", "Subtitle": "YOU WIN.", "Human Translation": "엄마가 이겼어요" },
  { "Time": "6:32", "Subtitle": "RORY, I LOVE YOU. I'D TAKE A BULLET FOR YOU.", "Human Translation": "엄마는 널 사랑해 총알도 막아줄 수 있어" },
  { "Time": "8:19", "Subtitle": "NOPE.", "Human Translation": "- 그럼 걱정할 게 없는 거죠? - 네" },
  { "Time": "9:01", "Subtitle": "I'LL GIVE YOU A HINT -- IT'S NOT YOUR LIFE!", "Human Translation": "힌트 하나 드리죠 미셸 인생은 아니에요" },
  { "Time": "9:52", "Subtitle": "ARE THOSE -- No. It would be too...", "Human Translation": "- 혹시 저 사람들이… - 설마요, 그럼 너무…" },
  { "Time": "11:28", "Subtitle": "RORY! HELLO! SORRY I'M LATE.", "Human Translation": "- 로리, 왔구나! - 늦어서 죄송해요" },
  { "Time": "12:54", "Subtitle": "THAT IT'S A GOOD WALK SPOILED.", "Human Translation": "산책은 끝났다는 정도요" },
  { "Time": "14:19", "Subtitle": "SOOKIE! WHAT?", "Human Translation": "- 수키, 잠깐만요! - 뭘요?" },
  { "Time": "15:20", "Subtitle": "YOU SUCK AT THIS GAME.", "Human Translation": "이 게임에 약하구나" },
  { "Time": "15:56", "Subtitle": "THAT -- THAT -- WILL WORK.", "Human Translation": "그럼 되겠네요" },
  { "Time": "17:12", "Subtitle": "QUITE A DAY, HUH? I DON'T WANT TO TALK --", "Human Translation": "- 대단한 하루였지? - 말하고 싶지 않아" },
  { "Time": "18:44", "Subtitle": "I KNOW. SHE TALKS ABOUT THAT ALL THE TIME. SHE DOES?", "Human Translation": "- 알아요, 항상 얘기하거든요 - 네 엄마가?" },
  { "Time": "20:54", "Subtitle": "SHE WANTED TO LEARN GOLF. I THINK SHE'S TAKEN TO IT QUITE WELL.", "Human Translation": "골프를 배우고 싶다더군 적응이 빠른 것 같아" },
  { "Time": "22:39", "Subtitle": "WHY? I HATE THE SWANS.", "Human Translation": "- 저 새 근처가 갈 수 없어요 - 왜요? - 난 백조가 싫어요" },
  { "Time": "24:32", "Subtitle": "SO, WE HEAR YOU'RE ATTENDING CHILTON. I JUST STARTED.", "Human Translation": "- 칠튼에 다닌다면서? - 이제 시작했어요" },
  { "Time": "25:46", "Subtitle": "GRANDMA GAVE IT TO ME. OH, NOW, THAT'S JUST MEAN.", "Human Translation": "할머니가 줬어 - 너무 심했네" },
  { "Time": "26:35", "Subtitle": "YOU HAD A BIG LUNCH AT THE CLUB? YEP. IT WAS QUITE GOOD.", "Human Translation": "- 클럽에서 점심을 먹었어? - 응, 꽤 맛있었어" },
  { "Time": "27:12", "Subtitle": "I DON'T KNOW. IT WAS PRETTY. GRANDPA AND I TALKED A LOT.", "Human Translation": "골프장도 예뻤고 할아버지와 얘기도 많이 했어" },
  { "Time": "30:40", "Subtitle": "NO. HE'S JUST FOUND THIS BOOK WE WERE TALKING ABOUT.", "Human Translation": "아니, 우리가 얘기하던 책을 찾으셨대" },
  { "Time": "32:05", "Subtitle": "I WAS THINKING YOUR GOLFING EXPEDITION SHOULD TOTALLY COUNT AS A DINNER.", "Human Translation": "네 골프 모험으로 저녁식사를 때우는 거야" },
  { "Time": "33:40", "Subtitle": "YOU'RE CRACKED!", "Human Translation": "엄만 미쳤어!" },
  { "Time": "35:03", "Subtitle": "IT OCCURRED TO MY MOTHER, THOUGH. GOD, I HATE THAT SHE WAS RIGHT.", "Human Translation": "엄마는 거기까지 생각했지 엄마 말이 맞을 땐 화가 나" },
  { "Time": "36:11", "Subtitle": "JACKSON, WAIT! NO!", "Human Translation": "- 잭슨, 기다려요! - 싫어요!" },
  { "Time": "39:40", "Subtitle": "IF IT MAKES YOU FEEL BETTER, I THINK I GOT A FUNGUS FROM THE STEAM ROOM.", "Human Translation": "기분이 좋아질진 모르겠지만 사우나 때문에 피부가 간지러워" },
  { "Time": "41:46", "Subtitle": "IT'S IN MY OFFICE IF YOU WANNA SEE THEM.", "Human Translation": "- 농담이시죠? - 지금 내 서재에 있단다 세상에, 빨리 보고 싶어요" }
];

const EP4_DATA = [
  { "Time": "2s", "Subtitle": "THAT'S NICE. THANK YOU.", "Human Translation": "‎- 잘 마시네 ‎- 고마워" },
  { "Time": "2:02", "Subtitle": "WHAT? IT'S 7:10!", "Human Translation": "‎- 뭐? ‎- 7시 10분" },
  { "Time": "2:52", "Subtitle": "IT'S 7:16.", "Human Translation": "‎- 괜찮은 옷은 다 더러워 ‎- 7시 16분" },
  { "Time": "4:14", "Subtitle": "I REMEMBER IT BEING SMALLER. YEAH. AND LESS...", "Human Translation": "‎- 더 작았던 것 같은데 ‎- 맞아" },
  { "Time": "5:30", "Subtitle": "WHICH IS... THE BIG, SCARY ONE.", "Human Translation": "‎크고 무서운 건물" },
  { "Time": "7:51", "Subtitle": "I-I'M LORELAI GILMORE.", "Human Translation": "‎안녕하세요? ‎로렐라이 길모어예요" },
  { "Time": "10:10", "Subtitle": "WELL, I DON'T THINK", "Human Translation": "‎핸린 씨도 바쁘실 텐데" },
  { "Time": "13:18", "Subtitle": "CHILTON HAS ONE OF THE HIGHEST ACADEMIC STANDARDS", "Human Translation": "‎칠튼의 교육 수준은" },
  { "Time": "16:12", "Subtitle": "I ALREADY HAD THE LONGEST DAY OF MY LIFE, AND IT'S ONLY 10:00. THERE'S NO COFFEE.", "Human Translation": "‎고된 하루였는데 아직도 ‎10시라니" },
  { "Time": "21:17", "Subtitle": "IT WAS...A \"D.\" I GOT A \"D.\"", "Human Translation": "‎D야, D를 받았다고" },
  { "Time": "29:11", "Subtitle": "NO! I GOT HIT BY A DEER! HOW DO YOU GET HIT BY A DEER?", "Human Translation": "‎- 아니, 사슴이 부딪쳤어! ‎- 어떻게 사슴이 부딪쳐?" },
  { "Time": "30:23", "Subtitle": "YOU HIT A DEER? I GOT HIT BY A DEER.", "Human Translation": "‎- 사슴을 쳤다고? ‎- 아뇨, 사슴이 와서 부딪쳤어요" },
  { "Time": "33:00", "Subtitle": "RORY, WHAT HAPPENED?", "Human Translation": "‎로리, 무슨 일이야?" },
  { "Time": "37:04", "Subtitle": "YOU GOT HIT BY A DEER?", "Human Translation": "‎사슴이 와서 부딪쳤다고?" },
  { "Time": "42:56", "Subtitle": "Anyway, see you in class. Bye.", "Human Translation": "‎'어쨌든 학교에서 보자, 안녕'" }
];

export const EPISODES: EpisodeMetadata[] = [
  {
    id: "s01e01",
    name: "Pilot",
    data: EP1_DATA
  },
  {
    id: "s01e02",
    name: "The Lorelais' First Day at Chilton",
    data: EP2_DATA
  },
  {
    id: "s01e03",
    name: "Kill Me Now",
    data: EP3_DATA
  },
  {
    id: "s01e04",
    name: "The Deer Hunters",
    data: EP4_DATA
  }
];
